### ISSUE TITLE
pypi out-of-date?

### ISSUE THREAD

**Issue by andrewcorrigan** [inducer/modepy#1] opened 2016-10-12 13:31 UTC
Installing modepy via `pip3 install git+https://github.com/inducer/modepy.git` works, but when I just do `pip3 install modepy` the error below occurs.  I wonder if https://pypi.python.org/pypi/modepy could be updated?
```
Collecting modepy
  Using cached modepy-2013.3.tar.gz
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.35.tar.gz
    Extracting in /var/folders/58/s1wjt0qn3wz6_v3zmtbmmdcm0005yr/T/tmpwv7us9pv
    Traceback (most recent call last):
      File "/private/var/folders/58/s1wjt0qn3wz6_v3zmtbmmdcm0005yr/T/pip-build-nqyz4i2r/modepy/distribute_setup.py", line 150, in use_setuptools
        raise ImportError
    ImportError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/58/s1wjt0qn3wz6_v3zmtbmmdcm0005yr/T/pip-build-nqyz4i2r/modepy/setup.py", line 68, in <module>
        main()
      File "/private/var/folders/58/s1wjt0qn3wz6_v3zmtbmmdcm0005yr/T/pip-build-nqyz4i2r/modepy/setup.py", line 6, in main
        distribute_setup.use_setuptools()
      File "/private/var/folders/58/s1wjt0qn3wz6_v3zmtbmmdcm0005yr/T/pip-build-nqyz4i2r/modepy/distribute_setup.py", line 152, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "/private/var/folders/58/s1wjt0qn3wz6_v3zmtbmmdcm0005yr/T/pip-build-nqyz4i2r/modepy/distribute_setup.py", line 132, in _do_download
        _build_egg(egg, tarball, to_dir)
      File "/private/var/folders/58/s1wjt0qn3wz6_v3zmtbmmdcm0005yr/T/pip-build-nqyz4i2r/modepy/distribute_setup.py", line 105, in _build_egg
        _extractall(tar)
      File "/private/var/folders/58/s1wjt0qn3wz6_v3zmtbmmdcm0005yr/T/pip-build-nqyz4i2r/modepy/distribute_setup.py", line 500, in _extractall
        self.chown(tarinfo, dirpath)
    TypeError: chown() missing 1 required positional argument: 'numeric_owner'
```

**Comment by inducer** [comment] 2016-10-12 15:14
Thanks for the poke. Just released 2016.1.1. Reopen this if the issue is not addressed by that.

**Closed by inducer** 2016-10-12 15:14 UTC
